apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: fusionauth
  name: fusionauth
spec:
  ports:
    - name: "9011"
      port: 9011
      targetPort: 9011
    - name: 9011-tcp
      port: 9011
      targetPort: 9011
  selector:
    io.kompose.service: fusionauth
