apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: search
  name: search
spec:
  ports:
    - name: "9200"
      port: 9200
      targetPort: 9200
    - name: "9600"
      port: 9600
      targetPort: 9600
  selector:
    io.kompose.service: search
